// voss_tracks.js — playlist manifest (GitHub Pages can't auto-list folders)

window.VOSS_TRACKS = [
  "Not Found NYC - Vóss Vol. 1 - 01 psalms.mp3",
  "Not Found NYC - Vóss Vol. 1 - 02 sleep dealer.mp3",
  "Not Found NYC - Vóss Vol. 1 - 03 weridcore-memories.mp3",
  "Not Found NYC - Vóss Vol. 1 - 04 lichenwake.mp3",
  "Not Found NYC - Vóss Vol. 1 - 05 rootnoise.mp3",
  "Not Found NYC - Vóss Vol. 1 - 06 pastel riot.mp3",
  "Not Found NYC - Vóss Vol. 1 - 07 rue synthèse.mp3",
  "Not Found NYC - Vóss Vol. 1 - 08 (untitled dream fragment).mp3",
  "Not Found NYC - Vóss Vol. 1 - 09 world muzak.mp3",

  "Not Found NYC - Vóss Vol. 2 - 01 sun bleed carousels.mp3",
  "Not Found NYC - Vóss Vol. 2 - 02 cryostasis aperture.mp3",
  "Not Found NYC - Vóss Vol. 2 - 03 serenity-now.mp3",
  "Not Found NYC - Vóss Vol. 2 - 04 bio$.mp3",
  "Not Found NYC - Vóss Vol. 2 - 05 apricot.mp3",
  "Not Found NYC - Vóss Vol. 2 - 06 iris.mp3",
  "Not Found NYC - Vóss Vol. 2 - 07 trilobite circle.mp3",
  "Not Found NYC - Vóss Vol. 2 - 08 (lost language sketch).mp3",
  "Not Found NYC - Vóss Vol. 2 - 09 But I Can Still Repent Though, Right-.mp3",

  "Not Found NYC - Vóss Vol. 3 - 01 lapis.mp3",
  "Not Found NYC - Vóss Vol. 3 - 02 title flight.mp3",
  "Not Found NYC - Vóss Vol. 3 - 03 Waste-Management.mp3",
  "Not Found NYC - Vóss Vol. 3 - 04 sunbeams.mp3",
  "Not Found NYC - Vóss Vol. 3 - 05 sadness across the land.mp3",
  "Not Found NYC - Vóss Vol. 3 - 06 heart throbbing.mp3",
  "Not Found NYC - Vóss Vol. 3 - 07 nose bleeds.mp3",
  "Not Found NYC - Vóss Vol. 3 - 08 (outside molnar's safeway).mp3",
  "Not Found NYC - Vóss Vol. 3 - 09 poppy seeds.mp3",

  "Not Found NYC - Vóss Vol. 4 - 01 FOUNTAINS OF THE GODS.mp3",
  "Not Found NYC - Vóss Vol. 4 - 02 ZEUS.mp3",
  "Not Found NYC - Vóss Vol. 4 - 03 POSEIDON.mp3",
  "Not Found NYC - Vóss Vol. 4 - 04 HADES.mp3",
  "Not Found NYC - Vóss Vol. 4 - 05 APOLLO.mp3",
  "Not Found NYC - Vóss Vol. 4 - 06 HEPHAESTUS.mp3",
  "Not Found NYC - Vóss Vol. 4 - 07 ATHENA.mp3",
  "Not Found NYC - Vóss Vol. 4 - 08 HERMES.mp3",
  "Not Found NYC - Vóss Vol. 4 - 09 MEDUSA.mp3",

  "Not Found NYC - Vóss Vol. 5 - 01 fear not, I am with you.mp3",
  "Not Found NYC - Vóss Vol. 5 - 02 happy world, sad mind.mp3",
  "Not Found NYC - Vóss Vol. 5 - 03 red alert, awof.mp3",
  "Not Found NYC - Vóss Vol. 5 - 04 people who live in glass houses, shouldn't throw stones.mp3",
  "Not Found NYC - Vóss Vol. 5 - 05 let he who is without sin cast the first stone.mp3",
  "Not Found NYC - Vóss Vol. 5 - 06 the red light never turns off.mp3",
  "Not Found NYC - Vóss Vol. 5 - 07 the Lord is my light and my salvation; whom shall i fear-.mp3",
  "Not Found NYC - Vóss Vol. 5 - 08 I am the way, and the truth, and the life.mp3",
  "Not Found NYC - Vóss Vol. 5 - 09 GOD BLE$$ AMERIKKA.mp3",

  "Not Found NYC - Vóss Vol. 6 - 01 Residence Inn.mp3",
  "Not Found NYC - Vóss Vol. 6 - 02 Comfortable Melancholy.mp3",
  "Not Found NYC - Vóss Vol. 6 - 03 Midnight Parallax.mp3",
  "Not Found NYC - Vóss Vol. 6 - 04 South of Heaven, North of the Border.mp3",
  "Not Found NYC - Vóss Vol. 6 - 05 Dolphin Funeral Protocol.mp3",
  "Not Found NYC - Vóss Vol. 6 - 06 Motel Seraphim.mp3",
  "Not Found NYC - Vóss Vol. 6 - 07 Sleep Architecture.mp3",
  "Not Found NYC - Vóss Vol. 6 - 08 Heat Death of a Heart.mp3",
  "Not Found NYC - Vóss Vol. 6 - 09 Salutations, Gypsies.mp3",
  "Not Found NYC - Vóss Vol. 6 - 10 Sleep Architecture (Remix).mp3"
];
